version: 0.2
language": en
words:
  - shivam
  - antfu
  - classpath
  - deoptimize
  - vueuse
  - nprogress
  - scroller
  - khattar
  - kolkata
  - frontmatter
  - autowires
  - checkpointing
  - snapshotting
  - CRIU
  - deoptimization
  - javadoc
  - PRNGs
  - deallocated
  - containerised
  - microbenchmark
  - pseudorandomness
  - quarkus
  - micronaut
patterns:
  - name: nunjucksExpression
    pattern: /{%.*?%}/gis
  - name: markdownCodeBlock
    pattern: /`{3}[\s\S]*?`{3}(?=\n|$)/gi
  - name: markdownInlineCode
    pattern: /`[^`]*`/gi
  - name: properNouns
    pattern: /(?<=\s|^|[^\w\s])[A-Z][a-z]+(?=\s|$|[^\w\s])/g
ignoreRegExpList:
  - nunjucksExpression
  - markdownCodeBlock
  - markdownInlineCode
  - properNouns
